{% set name = "click-params" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-params-{{ version }}.tar.gz
  sha256: 44be00bccc569c864cccc2d3012de73ca428a58f44f23dbc4ced32f53109f6c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=0.12
  run:
    - python >=3.6
    - click >=7.0,<9.0    
    - validators >=0.18,<0.19

test:
  imports:
    - click_params
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://click-params.readthedocs.io/en/stable
  summary: A bunch of useful click parameter types
  license: Apache-2.0
  license_file: LICENSE
  description: |

    PyPI: [https://pypi.org/project/click-params/](https://pypi.org/project/click-params/)

  doc_url: https://click-params.readthedocs.io/en/stable
  dev_url: https://github.com/click-contrib/click_params

extra:
  recipe-maintainers:
    - xylar
    - sodre
    - sugatoray
