{% set name = "click-params" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0e6b03b0cca3811d08102e1f0ce3d7c674d583637bc475a07629fe0d28c6a2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1,<2
  run:
    - click >=7.0,<8.0
    - python >=3.6,<4.0
    - validators >=0.14.1,<0.15.0

test:
  imports:
    - click_params
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://click-params.readthedocs.io/en/stable
  summary: A bunch of useful click parameter types
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
