{% set name = "click-params" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-params-{{ version }}.tar.gz
  sha256: 74b5c53e225c80037691aef5efa20b1a1fc9d342c85581e52c6cd3512dbcd987

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.7,<4.0
    - click >=7.0,<9.0
    - validators >=0.18,<0.19

test:
  imports:
    - click_params
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://click-params.readthedocs.io/en/stable
  summary: A bunch of useful click parameter types
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://click-params.readthedocs.io/en/stable
  dev_url: https://github.com/click-contrib/click_params

extra:
  recipe-maintainers:
    - sodre
    - sugatoray
